
skillMetadata:
  sections:
    - name: General Configs
      fields:
        - name: api-socket
          type: text
          label: desktop-automater socket path
          value: "/tmp/desktop-automater"
          placeholder: "desktop-automater socket path"
        - name: bspwm-socket
          type: text
          label: bspwm socket path
          value: "/tmp/bspwm_0_0-socket"
          placeholder: "bspwm spocket path"
    # - name: Login << Name of another section
    #   fields:
    #     - type: label
    #       label: Just a little bit of extra info for the user to understand following settings
    #     - name: username
    #       type: text
    #       label: Username
    #       value: ""
    #     - name: password
    #       type: password
    #       label: Password
    #       value: ""
